### ISSUE TITLE
Lacks python3 support

### ISSUE THREAD

**Issue by linganesan** [peragro/peragro-at#39]
Peragro-at works fine in python2 but not in python3! There are issues like....

> when  calls  pt t peragro-test-files/mesh/blender/cube1.blend  "Cube1-data(application/x-blender.mesh)" "image/png"

`    for key, value in self.__dict__.iteritems()]
AttributeError: 'dict' object has no attribute 'iteritems'
`

> when calls pt a peragro-test-files/mesh/blender/cube1.blend

`damn_at.analyzer.AnalyzerException: "E: Failed to analyze peragro-test-files/mesh/blender/cube1.blend because of a bytes-like object is required, not 'str'"
`
Does it really support python3?

**Comment by botanicvelious** [comment]
this error should be fixed now

**Comment by botanicvelious** [comment]
Looks like we got a new error!

>  DEBUG:yapsy_loaded_plugin_Blender_analyzer_0: b'Read new prefs: C:\\Users\\matthew\\AppData\\Roaming\\Blender Foundation\\Blender\\2.78\\config\\userpref.blend\r\nfound bundled python: C:\\Program Files\\Blender Foundation\\Blender\\2.78\\python\r\nread blend: C:\\development\\peragro\\peragro-test-files\\mesh\\blender\\cube1.blend\r\n\r\nBlender quit\r\n'
  DEBUG:yapsy_loaded_plugin_Blender_analyzer_0: b'Traceback (most recent call last):\r\n  File "<string>", line 2, in <module>\r\n  File "C:\\Python351\\lib\\site-packages\\damn_at-0.0.0.dev0-py3.5.egg\\damn_at\\analyzers\\mesh\\b-script-analyzerblend.py", line 202, in <module>\r\n    main()\r\n  File "C:\\Python351\\lib\\site-packages\\damn_at-0.0.0.dev0-py3.5.egg\\damn_at\\analyzers\\mesh\\b-script-analyzerblend.py", line 197, in main\r\n    data = SerializeThriftMsg(file_descr)\r\n  File "C:\\Python351\\lib\\site-packages\\damn_at-0.0.0.dev0-py3.5.egg\\damn_at\\serialization\\__init__.py", line 21, in SerializeThriftMsg\r\n    msg.write(protocolOut)\r\n  File "C:\\Python351\\lib\\site-packages\\damn_at-0.0.0.dev0-py3.5.egg\\damn_at\\serialization\\generated\\damn_types\\ttypes.py", line 776, in write\r\n    oprot.writeFieldBegin(\'file\', TType.STRUCT, 1)\r\n  File "C:\\Python351\\lib\\site-packages\\thrift\\protocol\\TBinaryProtocol.py", line 64, in writeFieldBegin\r\n    self.writeByte(type)\r\n  File "C:\\Python351\\lib\\site-packages\\thrift\\protocol\\TBinaryProtocol.py", line 103, in writeByte\r\n    self.trans.write(buff)\r\n  File "C:\\Python351\\lib\\site-packages\\thrift\\transport\\TTransport.py", line 228, in write\r\n    self._buffer.write(buf)\r\nTypeError: string argument expected, got \'bytes\'\r\nAL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead\r\n'
  DEBUG:yapsy_loaded_plugin_Blender_analyzer_0: 0
Traceback (most recent call last):
  File "C:\Python351\lib\site-packages\damn_at-0.0.0.dev0-py3.5.egg\damn_at\analyzer.py", line 160, in analyze_file
    file_descr = analyzer.plugin_object.analyze(an_uri)
  File "C:\Python351\lib\site-packages\damn_at-0.0.0.dev0-py3.5.egg\damn_at\analyzers\mesh\analyzerblend.py", line 48, in analyze
    data = str(stdoutdata).split('-**-')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Python351\lib\site-packages\damn_at-0.0.0.dev0-py3.5.egg\damn_at\analyzer.py", line 160, in analyze_file
    file_descr = analyzer.plugin_object.analyze(an_uri)
  File "C:\Python351\lib\site-packages\damn_at-0.0.0.dev0-py3.5.egg\damn_at\analyzers\mesh\analyzerblend.py", line 48, in analyze
    data = str(stdoutdata).split('-**-')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python351\Scripts\pt-script.py", line 11, in <module>
    load_entry_point('damn-at==0.0.0.dev0', 'console_scripts', 'pt')()
  File "C:\Python351\lib\site-packages\damn_at-0.0.0.dev0-py3.5.egg\damn_at\cli.py", line 349, in main
    args.func(args)
  File "C:\Python351\lib\site-packages\damn_at-0.0.0.dev0-py3.5.egg\damn_at\cli.py", line 105, in <lambda>
    args.store
  File "C:\Python351\lib\site-packages\damn_at-0.0.0.dev0-py3.5.egg\damn_at\cli.py", line 82, in analyze
    descr = analyzer.analyze_file(path)
  File "C:\Python351\lib\site-packages\damn_at-0.0.0.dev0-py3.5.egg\damn_at\analyzer.py", line 169, in analyze_file
    raise AnalyzerException("E: Failed to analyze %s because of %s" % (an_uri, str(ex)))
damn_at.analyzer.AnalyzerException: 'E: Failed to analyze peragro-test-files\\mesh\\blender\\cube1.blend because of list index out of range'

**Comment by botanicvelious** [comment]
try latest version should work
